### ISSUE TITLE
String array converted incorrectly

### ISSUE THREAD

**Issue by carlzoo** [Roger13/SwagDefGen#13]
How to reproduce:

```
{"the_strings":["abc","def"]}
```

Expected:
```
definitions: 
  the_strings: 
    type: array
    items: 
      type: string
```

Actual:
```
definitions: 
  the_strings: 
    type: array
    items: 
      type: object
      properties: 
        0: 
          type: string
        1: 
          type: string
        2: 
          type: string
```
